server:
  port: 65535
  
spring:
#  redis:
#    timeout: 0
#    database: 0
#    host: 192.168.1.117
#    port: 6379
#    password:
  datasource:
    url: jdbc:mysql://192.168.1.118:3306/demo-shiro-db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1qa@WS
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
#      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect    

### 日志
logging:
  level:
    root: info