spring:
  redis:
    timeout: 0
    database: 0
    host: 192.168.1.111
    port: 6379
    password:
    pool:
      max-active: 8
    pool:
      max-wait: -1
    pool:
      max-idle: 8
    pool:
      min-idle: 0